import type { Lead, Conversation } from "./types"

export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    name: "John Smith",
    email: "john.smith@acmecorp.com",
    linkedin: "linkedin.com/in/johnsmith",
    company: "Acme Corporation",
    notes: "Met at SaaS Conference. Interested in our enterprise plan. Has budget approval for Q3.",
    tags: ["Decision Maker", "Enterprise", "High Priority"],
    stage: "Contacted",
    createdAt: "2023-05-15T10:30:00Z",
    updatedAt: "2023-05-20T14:45:00Z",
  },
  {
    id: "lead-2",
    name: "Sarah Johnson",
    email: "sarah.j@techstartup.io",
    linkedin: "linkedin.com/in/sarahjohnson",
    company: "Tech Startup Inc.",
    notes: "Startup founder looking for scalable solution. Price sensitive but growing fast.",
    tags: ["Startup", "Decision Maker", "Technical"],
    stage: "New",
    createdAt: "2023-05-18T09:15:00Z",
    updatedAt: "2023-05-18T09:15:00Z",
  },
  {
    id: "lead-3",
    name: "Michael Chen",
    email: "mchen@globalinc.com",
    linkedin: "linkedin.com/in/michaelchen",
    company: "Global Inc.",
    notes: "Technical lead evaluating our API integration capabilities. Needs documentation and sample code.",
    tags: ["Technical", "Enterprise", "API Integration"],
    stage: "Contacted",
    createdAt: "2023-05-10T11:20:00Z",
    updatedAt: "2023-05-17T16:30:00Z",
  },
  {
    id: "lead-4",
    name: "Emily Rodriguez",
    email: "emily.r@marketingpros.com",
    linkedin: "linkedin.com/in/emilyrodriguez",
    company: "Marketing Pros",
    notes: "Marketing agency looking for white-label solution for their clients. Potential for volume discount.",
    tags: ["Agency", "White Label", "Follow Up"],
    stage: "Converted",
    createdAt: "2023-04-28T13:45:00Z",
    updatedAt: "2023-05-19T10:15:00Z",
  },
  {
    id: "lead-5",
    name: "David Kim",
    email: "dkim@retailgroup.com",
    linkedin: "linkedin.com/in/davidkim",
    company: "Retail Group",
    notes: "Retail chain with 50+ locations. Looking to modernize their customer engagement strategy.",
    tags: ["Enterprise", "Retail", "Budget Holder"],
    stage: "Contacted",
    createdAt: "2023-05-05T15:30:00Z",
    updatedAt: "2023-05-16T11:20:00Z",
  },
  {
    id: "lead-6",
    name: "Lisa Wang",
    email: "lisa.wang@innovatehealth.org",
    linkedin: "linkedin.com/in/lisawang",
    company: "Innovate Health",
    notes: "Healthcare startup with strict compliance requirements. Need to discuss HIPAA compliance features.",
    tags: ["Healthcare", "Compliance", "Technical"],
    stage: "New",
    createdAt: "2023-05-19T08:45:00Z",
    updatedAt: "2023-05-19T08:45:00Z",
  },
  {
    id: "lead-7",
    name: "Robert Taylor",
    email: "rtaylor@constructionco.com",
    linkedin: "linkedin.com/in/roberttaylor",
    company: "Construction Co.",
    notes: "Traditional company looking to digitize their workflows. Slow decision-making process expected.",
    tags: ["Traditional Industry", "Digital Transformation"],
    stage: "Lost",
    createdAt: "2023-04-15T09:30:00Z",
    updatedAt: "2023-05-12T14:20:00Z",
  },
  {
    id: "lead-8",
    name: "Jennifer Adams",
    email: "jennifer@edtechleaders.edu",
    linkedin: "linkedin.com/in/jenniferadams",
    company: "EdTech Leaders",
    notes: "Education technology company. Interested in our API for integration with their LMS platform.",
    tags: ["Education", "API Integration", "Technical"],
    stage: "Converted",
    createdAt: "2023-04-20T11:15:00Z",
    updatedAt: "2023-05-18T15:45:00Z",
  },
  {
    id: "lead-9",
    name: "Thomas Wilson",
    email: "twilson@financepro.com",
    linkedin: "linkedin.com/in/thomaswilson",
    company: "Finance Pro",
    notes: "Financial services firm. Security and compliance are top priorities. Long sales cycle expected.",
    tags: ["Financial Services", "Security", "Enterprise"],
    stage: "Contacted",
    createdAt: "2023-05-08T10:00:00Z",
    updatedAt: "2023-05-15T13:30:00Z",
  },
  {
    id: "lead-10",
    name: "Olivia Martinez",
    email: "olivia.m@creativestudio.design",
    linkedin: "linkedin.com/in/oliviamartinez",
    company: "Creative Studio",
    notes: "Design agency looking for project management tools. Small team but potential for growth.",
    tags: ["Agency", "Design", "Small Business"],
    stage: "New",
    createdAt: "2023-05-17T14:20:00Z",
    updatedAt: "2023-05-17T14:20:00Z",
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    leadId: "lead-1",
    type: "email",
    content:
      "Sent initial outreach email introducing our platform and referencing our meeting at the SaaS Conference. Attached product brochure and pricing information for enterprise plan.",
    timestamp: "2023-05-15T14:30:00Z",
  },
  {
    id: "conv-2",
    leadId: "lead-1",
    type: "email",
    content:
      "John replied expressing interest in scheduling a demo. He mentioned that they're currently evaluating several solutions and have budget approval for Q3.",
    timestamp: "2023-05-16T09:45:00Z",
  },
  {
    id: "conv-3",
    leadId: "lead-1",
    type: "call",
    content:
      "Had a 30-minute discovery call. John explained their current challenges with scalability and integration. I highlighted our enterprise features and API capabilities. He seemed particularly interested in our SSO implementation.",
    timestamp: "2023-05-18T15:00:00Z",
    followUpDate: "2023-05-25T15:00:00Z",
  },
  {
    id: "conv-4",
    leadId: "lead-3",
    type: "email",
    content: "Sent introduction email with technical documentation and API reference guide as requested by Michael.",
    timestamp: "2023-05-10T16:30:00Z",
  },
  {
    id: "conv-5",
    leadId: "lead-3",
    type: "call",
    content:
      "Technical call with Michael and his development team. They had specific questions about our API rate limits and authentication methods. Promised to send sample integration code.",
    timestamp: "2023-05-15T11:00:00Z",
  },
  {
    id: "conv-6",
    leadId: "lead-3",
    type: "email",
    content:
      "Sent follow-up email with sample code snippets for API integration and invited them to join our developer Slack community.",
    timestamp: "2023-05-17T09:20:00Z",
    followUpDate: "2023-05-24T09:00:00Z",
  },
  {
    id: "conv-7",
    leadId: "lead-4",
    type: "linkedin",
    content:
      "Connected with Emily on LinkedIn and sent a message mentioning our white-label solutions for marketing agencies.",
    timestamp: "2023-04-28T15:30:00Z",
  },
  {
    id: "conv-8",
    leadId: "lead-4",
    type: "email",
    content:
      "Emily requested more information about our white-label options and pricing for agencies. Sent detailed information and case studies from other agency clients.",
    timestamp: "2023-05-02T10:15:00Z",
  },
  {
    id: "conv-9",
    leadId: "lead-4",
    type: "call",
    content:
      "Demo call with Emily and her team. Showed agency dashboard and client management features. They were impressed with the customization options.",
    timestamp: "2023-05-10T14:00:00Z",
  },
  {
    id: "conv-10",
    leadId: "lead-4",
    type: "email",
    content:
      "Emily confirmed they want to proceed with our agency plan! Sent contract for signature and scheduled onboarding call.",
    timestamp: "2023-05-19T09:30:00Z",
    followUpDate: "2023-05-26T14:00:00Z",
  },
  {
    id: "conv-11",
    leadId: "lead-5",
    type: "email",
    content:
      "Initial outreach to David based on referral from existing retail client. Highlighted our success with similar retail chains.",
    timestamp: "2023-05-05T16:45:00Z",
  },
  {
    id: "conv-12",
    leadId: "lead-5",
    type: "call",
    content:
      "Brief call with David. He explained their current customer engagement challenges across 50+ locations. Scheduled a more detailed discovery call with his team next week.",
    timestamp: "2023-05-12T11:30:00Z",
    followUpDate: "2023-05-19T10:00:00Z",
  },
  {
    id: "conv-13",
    leadId: "lead-7",
    type: "email",
    content: "Sent introduction and information about our digital transformation solutions for construction companies.",
    timestamp: "2023-04-15T14:20:00Z",
  },
  {
    id: "conv-14",
    leadId: "lead-7",
    type: "call",
    content:
      "Call with Robert. They're interested but have concerns about implementation complexity and training requirements for their field staff.",
    timestamp: "2023-04-25T13:00:00Z",
  },
  {
    id: "conv-15",
    leadId: "lead-7",
    type: "email",
    content:
      "Robert informed us they've decided to postpone their digital transformation initiative until next year due to budget constraints.",
    timestamp: "2023-05-12T09:15:00Z",
  },
  {
    id: "conv-16",
    leadId: "lead-8",
    type: "linkedin",
    content: "Connected with Jennifer after she attended our webinar on API integrations for education platforms.",
    timestamp: "2023-04-20T15:45:00Z",
  },
  {
    id: "conv-17",
    leadId: "lead-8",
    type: "email",
    content:
      "Jennifer requested technical documentation and information about our education sector clients. Sent materials and offered to connect her with our education specialist.",
    timestamp: "2023-04-24T10:30:00Z",
  },
  {
    id: "conv-18",
    leadId: "lead-8",
    type: "call",
    content:
      "Technical demo with Jennifer and her development team. They were impressed with our LMS integration capabilities and compliance with education data standards.",
    timestamp: "2023-05-05T14:00:00Z",
  },
  {
    id: "conv-19",
    leadId: "lead-8",
    type: "email",
    content:
      "Jennifer confirmed they want to move forward! Sent contract and scheduled implementation kickoff meeting.",
    timestamp: "2023-05-18T11:30:00Z",
    followUpDate: "2023-05-25T14:00:00Z",
  },
  {
    id: "conv-20",
    leadId: "lead-9",
    type: "email",
    content:
      "Sent targeted outreach to Thomas highlighting our security features and compliance certifications relevant to financial services.",
    timestamp: "2023-05-08T13:15:00Z",
  },
  {
    id: "conv-21",
    leadId: "lead-9",
    type: "call",
    content:
      "Initial call with Thomas. He's primarily concerned about data security, regulatory compliance, and audit trails. Promised to send our security whitepaper and compliance documentation.",
    timestamp: "2023-05-15T10:00:00Z",
    followUpDate: "2023-05-22T10:00:00Z",
  },
]
